### ISSUE TITLE
Failed with Ruby3.2

### ISSUE THREAD

**Issue by m-mochida-developer** [mataku/danger-ktlint#16]
Hello,

We use Ruby 3.2 and danger-ktlint failed.
```
plugin.rb:180:in `ktlint_result_files': undefined method `exists?' for File:Class (NoMethodError)
      if !report_file.nil? && !report_file.empty? && File.exists?(report_file)
                                                         ^^^^^^^^
```
Ruby3.2 obsoletes `File.exists`.
[Ruby 3.2.0 Released](https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/)

**Comment by mataku** [comment]
@m-mochida-developer released as v0.0.9 with this fix. Thanks for your help!

https://rubygems.org/gems/danger-ktlint/versions/0.0.9
