### ISSUE TITLE
Specify ktlint limit for number of violations

### ISSUE THREAD

**Issue by Urmil-Ally** [mataku/danger-ktlint#5]
Is it possible to specify the limit of errors that are printed in the comments for the Bitbucket server? 
I see the option available but I get the error below. 

[!] Invalid `Dangerfile` file: undefined method `limit=' for #<Danger::Dangerfile:0x00007fe2e8060040>\e[0m
 from Dangerfile:66
 ktlint.limit = 10 -> here. 
 ktlint.lint
 
Is there a better way of specifying options?

**Comment by mataku** [comment]
@Urmil-Ally 
Sorry, I just released v0.0.3, including a feature which can specify the number of comments.

See: https://github.com/mataku/danger-ktlint/blob/master/README.md#set-maximum-number-of-comments-of-ktlint-results

Try it!
