### ISSUE TITLE
Support only process output files

### ISSUE THREAD

**Issue by ffgiraldez** [mataku/danger-ktlint#6]
Hi

We use in our team danger in our android development, and wants to include ktlint in our danger file, but we already run ktlint before parse danger so it run twice, could be possible to configure it like https://github.com/loadsmart/danger-android_lint to only parse previously generated output file and skip the ktlint task?

**Comment by mataku** [comment]
👍 

I'll try tomorrow or the next day.

**Comment by ffgiraldez** [comment]
thanks you @mataku ❤️

**Comment by ffgiraldez** [comment]
Hi @mataku I tested v0.0.4 with `ktlint.skip_lint = true` and CI fails because I don't have ktlint installed, if skip_lint == true, the check of ktlint binaries should be avoided.

I'm using https://github.com/JLLeitschuh/ktlint-gradle so my CI builds don't use ktlint binaries

**Comment by mataku** [comment]
>  if skip_lint == true, the check of ktlint binaries should be avoided.

My mistake, I forgot to erase it. Released a fixed version as v0.0.5 🙏

**Comment by ffgiraldez** [comment]
work like a charm, thanks
